### ISSUE TITLE
train.py is unable  to find image sequences while training -- GOOGLE COLAB

### ISSUE THREAD

**Issue by dikshantjn** [NVlabs/imaginaire#103]
I am running on google colab with a custom dataset for Pose training in FewShot_vid2vid

CUDA: 11.2

I have already preprocessed the data and created the lmdb files.
NOTE: The lmdb files and the images are saved on drive.
When I run the **train.py**, I encounter the following error:
`
/content/drive/My Drive/imaginaire
Using random seed 2
Training with 1 GPUs.
Make folder logs/2021_1103_2124_22_ampO1
cudnn benchmark: True
cudnn deterministic: False
LMDB ROOT ['datasets/youtube_dancing/lmdb/train']
Creating metadata
['human_instance_maps', 'images', 'poses-openpose']
Data file extensions: {'images': 'jpg', 'poses-openpose': 'json', 'human_instance_maps': 'png'}
Searching in dir: images
Found 0 sequences
Found 0 files
Folder at datasets/youtube_dancing/lmdb/train/images opened.
Folder at datasets/youtube_dancing/lmdb/train/poses-openpose opened.
Folder at datasets/youtube_dancing/lmdb/train/human_instance_maps opened.
Num datasets: 1
Num sequences: 0
Max sequence length: 0
Requested sequence length (4) + few shot K (1) > max sequence length (0). 
Reduced sequence length to -1
Epoch length: 0
LMDB ROOT ['datasets/youtube_dancing/lmdb/val']
Creating metadata
['human_instance_maps', 'images', 'poses-openpose']
Data file extensions: {'images': 'jpg', 'poses-openpose': 'json', 'human_instance_maps': 'png'}
Searching in dir: images
Found 0 sequences
Found 0 files
Folder at datasets/youtube_dancing/lmdb/val/images opened.
Folder at datasets/youtube_dancing/lmdb/val/poses-openpose opened.
Folder at datasets/youtube_dancing/lmdb/val/human_instance_maps opened.
Num datasets: 1
Num sequences: 0
Max sequence length: 0
Requested sequence length (2) + few shot K (1) > max sequence length (0). 
Reduced sequence length to -1
Epoch length: 0
Train dataset length: 0
Val dataset length: 0
Traceback (most recent call last):
  File "/content/drive/My Drive/imaginaire/train.py", line 169, in <module>
    main()
  File "/content/drive/My Drive/imaginaire/train.py", line 89, in main
    train_data_loader, val_data_loader = get_train_and_val_dataloader(cfg, args.seed)
  File "/content/drive/My Drive/imaginaire/imaginaire/utils/dataset.py", line 81, in get_train_and_val_dataloader
    train_data_loader = _get_data_loader(cfg, train_dataset, cfg.data.train.batch_size, drop_last=True, seed=seed)
  File "/content/drive/My Drive/imaginaire/imaginaire/utils/dataset.py", line 56, in _get_data_loader
    data_loader = torch.utils.data.DataLoader(
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 102, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
`

**Is there a specific folder to copy the image data and lmdb to? ** 
or
**Any other way to solve this?**

Thank you

**Comment by Quanta-of-solitude** [comment]
how did you solve this issue?
