### ISSUE TITLE
[Pose] Could we train on data preprocessed without --face and --hand?

### ISSUE THREAD

**Issue by dikshantjn** [NVlabs/imaginaire#104]
Can we train the fewshot_vid2vid without preprocessing the data using --face and --hand in openpose command on the preprocess.py? 

I have preprocessed data using the following openpose command:

`.\build\x64\Release\OpenPoseDemo.exe --display 0 --disable_blending --write_images PATH_TO_POSE_IMG --image_dir PATH_TO_IMG_DIR --write_json PATH_TO_JSON_DIR`

Do I need to preprocess data with --face and --hand flags for openpose or can I train without them?

**Comment by dikshantjn** [comment]
@arunmallya @tcwang0509 @mingyuliutw

**Comment by tcwang0509** [comment]
Yes you should be able to. Just remove the drawing of faces and hands in the corresponding vis functions.
