### ISSUE TITLE
Train with images without hand and face joints

### ISSUE THREAD

**Issue by kai0122** [NVlabs/imaginaire#105]
Hello,

I tried to run train.py with images and poses without hand and face data.
I removed the code that extracts hand and face data, and also remove the part that visualize them.
However, it keeps on telling me that I am passing "NoneType" data to the generator model.

Do you have any idea how could I solve it?

Thank you!

**Comment by kai0122** [comment]
When I tried to print out the data that returned.
It seems that all data["few_shot_label"], which is the ref_labels are all None.
Do you have any way to solve it?

Thank you!

**Comment by tcwang0509** [comment]
Should be fixed with the latest commit now.
