### ISSUE TITLE
[FSVID2VID - - POSE ] TypeError: conv2d() received an invalid combination of arguments 

### ISSUE THREAD

**Issue by dikshantjn** [NVlabs/imaginaire#106]
I am trying to train a custom pose dataset using **only openpose**.

I get the following error:
`
/content/drive/My Drive/imaginaire
Using random seed 2
Training with 1 GPUs.
Make folder logs/2021_1110_2255_34_ampO1
cudnn benchmark: True
cudnn deterministic: False
LMDB ROOT ['dataset/train']
Creating metadata
['human_instance_maps', 'images', 'poses-openpose']
Data file extensions: {'images': 'jpg', 'poses-openpose': 'json', 'human_instance_maps': 'png'}
Searching in dir: images
Found 336 sequences
Found 12934 files
Folder at dataset/train/images opened.
Folder at dataset/train/poses-openpose opened.
Folder at dataset/train/human_instance_maps opened.
Num datasets: 1
Num sequences: 336
Max sequence length: 40
Epoch length: 336
LMDB ROOT ['dataset/val']
Creating metadata
['human_instance_maps', 'images', 'poses-openpose']
Data file extensions: {'images': 'jpg', 'poses-openpose': 'json', 'human_instance_maps': 'png'}
Searching in dir: images
Found 40 sequences
Found 1524 files
Folder at dataset/val/images opened.
Folder at dataset/val/poses-openpose opened.
Folder at dataset/val/human_instance_maps opened.
Num datasets: 1
Num sequences: 40
Max sequence length: 40
Epoch length: 40
Train dataset length: 336
Val dataset length: 40
Using random seed 2
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True
    computed_on_the_fly: False
    is_mask: False
    pre_aug_ops: None
    post_aug_ops: None for input.
	Num. of channels in the input image: 3
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True
    computed_on_the_fly: False
    is_mask: False
    pre_aug_ops: None
    post_aug_ops: None for input.
Concatenate poses-openpose:
    ext: json
    num_channels: 3
    interpolator: None
    normalize: False
    pre_aug_ops: decode_json, convert::imaginaire.utils.visualization.pose::openpose_to_npy
    post_aug_ops: vis::imaginaire.utils.visualization.pose::draw_openpose_npy
    computed_on_the_fly: False
    is_mask: False for input.
Concatenate human_instance_maps:
    ext: png
    num_channels: 3
    is_mask: True
    normalize: False
    computed_on_the_fly: False
    pre_aug_ops: None
    post_aug_ops: None for input.
	Num. of channels in the input label: 3
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True
    computed_on_the_fly: False
    is_mask: False
    pre_aug_ops: None
    post_aug_ops: None for input.
	Num. of channels in the input image: 3
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True
    computed_on_the_fly: False
    is_mask: False
    pre_aug_ops: None
    post_aug_ops: None for input.
	Num. of channels in the input image: 3
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True
    computed_on_the_fly: False
    is_mask: False
    pre_aug_ops: None
    post_aug_ops: None for input.
	Num. of channels in the input image: 3
Initialized temporal embedding network with the reference one.
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True
    computed_on_the_fly: False
    is_mask: False
    pre_aug_ops: None
    post_aug_ops: None for input.
Concatenate poses-openpose:
    ext: json
    num_channels: 3
    interpolator: None
    normalize: False
    pre_aug_ops: decode_json, convert::imaginaire.utils.visualization.pose::openpose_to_npy
    post_aug_ops: vis::imaginaire.utils.visualization.pose::draw_openpose_npy
    computed_on_the_fly: False
    is_mask: False for input.
Concatenate human_instance_maps:
    ext: png
    num_channels: 3
    is_mask: True
    normalize: False
    computed_on_the_fly: False
    pre_aug_ops: None
    post_aug_ops: None for input.
	Num. of channels in the input label: 3
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True
    computed_on_the_fly: False
    is_mask: False
    pre_aug_ops: None
    post_aug_ops: None for input.
	Num. of channels in the input image: 3
Initialize net_G and net_D weights using type: xavier gain: 0.02
Using random seed 2
net_G parameter count: 91,147,294
net_D parameter count: 6,292,963
Use custom initialization for the generator.
Setup trainer.
Using automatic mixed precision training.
Augmentation policy: 
GAN mode: hinge
Perceptual loss:
	Mode: vgg19
Loss GAN                  Weight 1.0
Loss FeatureMatching      Weight 10.0
Loss Perceptual           Weight 10.0
Loss GAN_face             Weight 10.0
Loss FeatureMatching_face Weight 10.0
Loss Flow                 Weight 10.0
Loss Flow_L1              Weight 10.0
Loss Flow_Warp            Weight 10.0
Loss Flow_Mask            Weight 10.0
TRAIN DATASET :=  <imaginaire.trainers.fs_vid2vid.Trainer object at 0x7f553eec3fa0>
No checkpoint found.
Epoch 0 ...
Epoch length: 336
------ Now start training 4 frames -------
Traceback (most recent call last):
  File "/content/drive/My Drive/imaginaire/train.py", line 169, in <module>
    main()
  File "/content/drive/My Drive/imaginaire/train.py", line 129, in main
    for it, data in enumerate(train_data_loader):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/imaginaire/imaginaire/datasets/paired_videos.py", line 288, in __getitem__
    return self._getitem(index)
  File "/content/drive/My Drive/imaginaire/imaginaire/datasets/paired_few_shot_videos.py", line 303, in _getitem
    data = self.apply_ops(data, self.full_data_ops, full_data=True)
  File "/content/drive/My Drive/imaginaire/imaginaire/datasets/base.py", line 428, in apply_ops
    data = op(data)
  File "/content/drive/My Drive/imaginaire/imaginaire/model_utils/fs_vid2vid.py", line 108, in crop_face_from_data
    landmarks = data['landmarks-dlib68_xy']
KeyError: 'landmarks-dlib68_xy'
`

So I tried removing the **crop_face_from_data** from the config file, and now I get this error message:

```
TRAIN DATASET :=  <imaginaire.trainers.fs_vid2vid.Trainer object at 0x7f09ac9606a0>
No checkpoint found.
Epoch 0 ...
Epoch length: 336
------ Now start training 4 frames -------
Traceback (most recent call last):
  File "/content/drive/My Drive/imaginaire/train.py", line 169, in <module>
    main()
  File "/content/drive/My Drive/imaginaire/train.py", line 141, in main
    trainer.gen_update(
  File "/content/drive/My Drive/imaginaire/imaginaire/trainers/vid2vid.py", line 254, in gen_update
    net_G_output = self.net_G(data_t)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/My Drive/imaginaire/imaginaire/utils/trainer.py", line 195, in forward
    return self.module(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/My Drive/imaginaire/imaginaire/generators/fs_vid2vid.py", line 151, in forward
    self.weight_generator(ref_images, ref_labels, label, is_first_frame)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/My Drive/imaginaire/imaginaire/generators/fs_vid2vid.py", line 586, in forward
    self.encode_reference(ref_image, ref_label, label, k)
  File "/content/drive/My Drive/imaginaire/imaginaire/generators/fs_vid2vid.py", line 644, in encode_reference
    x_label = self.ref_label_first(ref_label)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/My Drive/imaginaire/imaginaire/layers/conv.py", line 142, in forward
    x = layer(x)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1120, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (NoneType, Tensor, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (NoneType, Tensor, Parameter, tuple, tuple, tuple, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (NoneType, Tensor, Parameter, tuple, tuple, tuple, int)

```

Here is the edited [yaml](https://drive.google.com/file/d/1GgsBxBsolkrDhmQNLB2qr_bbeMUXQCIX/view?usp=sharing) file attached.
Is there any way to solve this?

**Comment by dikshantjn** [comment]
@arunmallya @tcwang0509 @mingyuliutw

**Comment by tcwang0509** [comment]
Sorry it seems the config was incorrectly modified in some previous commit. Could you try [this config](https://drive.google.com/file/d/132nvOkgls2wB-CFEOH41iaoGGLWXfQGq/view?usp=sharing) instead?

**Comment by dikshantjn** [comment]
After updating the yaml file I now get the following error message:

```
TRAIN DATASET :=  <imaginaire.trainers.fs_vid2vid.Trainer object at 0x7f1c3818cd00>
No checkpoint found.
Epoch 0 ...
Epoch length: 336
------ Now start training 4 frames -------
Traceback (most recent call last):
  File "/content/drive/My Drive/imaginaire/train.py", line 169, in <module>
    main()
  File "/content/drive/My Drive/imaginaire/train.py", line 129, in main
    for it, data in enumerate(train_data_loader):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.9/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/imaginaire/imaginaire/datasets/paired_videos.py", line 288, in __getitem__
    return self._getitem(index)
  File "/content/drive/My Drive/imaginaire/imaginaire/datasets/paired_few_shot_videos.py", line 303, in _getitem
    data = self.apply_ops(data, self.full_data_ops, full_data=True)
  File "/content/drive/My Drive/imaginaire/imaginaire/datasets/base.py", line 428, in apply_ops
    data = op(data)
  File "/content/drive/My Drive/imaginaire/imaginaire/model_utils/fs_vid2vid.py", line 217, in crop_person_from_data
    label = remove_other_ppl(label, data['human_instance_maps'])
  File "/content/drive/My Drive/imaginaire/imaginaire/model_utils/fs_vid2vid.py", line 363, in remove_other_ppl
    valid = (openpose[0] > 0) | (openpose[1] > 0) | (openpose[2] > 0)
IndexError: index 0 is out of bounds for dimension 0 with size 0
```

Any idea how could I resolve this?

**Comment by grewe** [comment]
@tcwang0509 we really need your help on making any progress here.  There has been code that does not work and this is just one of the many issues we have had to tackle.  This is taking many weeks and we can not make progress and this is not in crunch time.   Can you please help us?   The incorrect yaml file was replaced with the one you gave us and this has led to more errors.   @arunmallya (can you help us out...I know you said someone else --tcwang is in charge of this project)?

**Comment by tcwang0509** [comment]
This mean your data format is different from what the network expects. I've verified the config is working using the [unit test data](https://github.com/NVlabs/imaginaire/tree/master/dataset/unit_test/raw/vid2vid/pose) without problems. Please double check your data format.

**Comment by grewe** [comment]
We have followed all the very sparse (not much) directions for preparation of the data --- we are only using Openpose as this is documented on your site as possible.   Is it possible for you to look at our data and tell us what you think.  Here is the `[directory.](https://drive.google.com/drive/folders/10dbLVDFqDrezuifWrCW3HN1x_fEIfDZ5?usp=sharing)`

It looks okay to us---please help.  This is for a student doing a semester long capstone project they need to graduate and the semester is ending start of December.  We are desperate.

**Comment by grewe** [comment]
Why are all the images in your [human_instances_maps](https://github.com/NVlabs/imaginaire/tree/master/dataset/unit_test/raw/vid2vid/pose/human_instance_maps/001_001)  of the the [unit test ](https://github.com/NVlabs/imaginaire/tree/master/dataset/unit_test/raw/vid2vid/pose)data black-- 
Here is an example of[ ours showing a skeleton](the unit test data)


Also -why do you not have multiple videos any only have 9 images in the flat directories unlike what we have where the images extracted from our videos are stored in a directory of that name for the images,  human_instances_maps and so directories?

**Comment by grewe** [comment]
Here is a depiction of our data to make things easier but, you can simply go to our directory to browse.

For each video i.e. lets look at  shallow_120_youtube_02_09_21_16_17.mpg we create subfolders in our /images   and /poses-openpose and /human_instance_maps with the name shallow_120_youtube_02_09_21_16_17_folder and store the respective image frame related data for the image frames (we number them img1, img2, and so on ) that is extracted from this video.


So for this example

-/images/shallow_120_youtube_02_9_21_16_17_folder[ looks like this ](https://drive.google.com/file/d/1HasmAB3oVcwrgbYw348xKFmZZWkQEExV/view?usp=sharing) AND you can [browse it here](https://drive.google.com/drive/folders/1al3UoO68zFZZWUhAowIvaLHmgVYKmk2m?usp=sharing)


-/poses-openpose/shallow_120_youtube_02_9_21_16_17_folder[ looks like this ](https://drive.google.com/file/d/1EDNC6oe4bfnS_QsTuJj5pF4S_-7Y3fnt/view?usp=sharing) AND you can [browse it here](https://drive.google.com/drive/folders/1iHmbl5yjuOJSOpJfIM09HgD0jM3WHvZs?usp=sharing)

-/human_instance_maps/shallow_120_youtube_02_9_21_16_17_folder[ looks like this ](https://drive.google.com/file/d/1UR7fPgE4vnFgMEEx0N8P3GCuroL_6iuI/view?usp=sharing) AND you can [browse it here](https://drive.google.com/drive/folders/1fdMeOfs5y0WnVGVt_G9sdvgNvI9DX6pL?usp=sharing)





DOES this look write to you?

**Comment by arunmallya** [comment]
Your config was wrong. Furthermore, `human_instance_maps` are supposed to contain "instance" ids, not the visualization of openpose. I have attached a config that works, the folder layout used (I'm using the folder loader, not lmdb here), and a sample output during training.
Dataset folder layout: [grewe.zip](https://github.com/NVlabs/imaginaire/files/7524041/grewe.zip)
Config used: [test.txt](https://github.com/NVlabs/imaginaire/files/7524044/test.txt)
You will want to change hyperparams such as `image_save_iter`, `snapshot_save_epoch`, `num_epochs_temporal_step`, and `initial_sequence_length`.

Output after 100 training iterations:
![epoch_00100_iteration_000000100](https://user-images.githubusercontent.com/838538/141388827-cd597b94-93ea-49e6-83c3-28934799ed68.jpeg)

I am closing this issue. Good luck.

**Comment by grewe** [comment]
please dont close this issue

we really need the help

**Comment by grewe** [comment]
Also on another issue had requested some documentation on the config file as there is none.  It is really hard to understand without spending hours and hours going through your code.

Is there any documentation of what each item in config does.

**Comment by grewe** [comment]
Is there any documentation of what will happen with different sized videos ---do we need to resize or is this something that is done in the code...is it influenced by the config file in any way?

**Comment by dikshantjn** [comment]
@arunmallya Thank you for your help with the previous issue. I tried running training through the config file you provided. It did train successfully but did not save any checkpoints for me to run inference on. Also if I manually change the code to save checkpoints, and edit config file to run inference I get the following error:
```
Using random seed 0
cudnn benchmark: True
cudnn deterministic: False
LMDB ROOT ['dataset/val/']
Creating metadata
['images', 'poses-openpose']
Data file extensions: {'images': 'jpg', 'poses-openpose': 'json'}
Searching in dir: images
Found 40 sequences
Found 1524 files
Folder at dataset/val/images opened.
Folder at dataset/val/poses-openpose opened.
Num datasets: 1
Num sequences: 40
Max sequence length: 40
Epoch length: 40
Using random seed 0
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
	Num. of channels in the input image: 3
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
Concatenate poses-openpose:
    ext: json
    num_channels: 3
    interpolator: None
    normalize: False
    pre_aug_ops: decode_json, convert::imaginaire.utils.visualization.pose::openpose_to_npy
    post_aug_ops: vis::imaginaire.utils.visualization.pose::draw_openpose_npy for input.
	Num. of channels in the input label: 3
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
	Num. of channels in the input image: 3
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
	Num. of channels in the input image: 3
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
	Num. of channels in the input image: 3
Initialized temporal embedding network with the reference one.
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
Concatenate poses-openpose:
    ext: json
    num_channels: 3
    interpolator: None
    normalize: False
    pre_aug_ops: decode_json, convert::imaginaire.utils.visualization.pose::openpose_to_npy
    post_aug_ops: vis::imaginaire.utils.visualization.pose::draw_openpose_npy for input.
	Num. of channels in the input label: 3
Concatenate images:
    ext: jpg
    num_channels: 3
    normalize: True for input.
	Num. of channels in the input image: 3
Initialize net_G and net_D weights using type: xavier gain: 0.02
Using random seed 0
net_G parameter count: 91,147,294
net_D parameter count: 5,598,018
Use custom initialization for the generator.
Opt D Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.0, 0.999)
    eps: 1e-08
    initial_lr: 0.0004
    lr: 0.0004
    weight_decay: 0
)
Setup trainer.
Using automatic mixed precision training.
Augmentation policy: 
GAN mode: hinge
Perceptual loss:
	Mode: vgg19
Loss GAN                  Weight 1.0
Loss FeatureMatching      Weight 10.0
Loss Perceptual           Weight 10.0
Loss Flow                 Weight 10.0
Loss Flow_L1              Weight 10.0
Loss Flow_Warp            Weight 10.0
Loss Flow_Mask            Weight 10.0
Done with loading the checkpoint.
configs for inference
finetune: True
finetune_iter: 100
few_shot_seq_index: 0
few_shot_frame_index: 0
driving_seq_index: 1
output dir:  projects/fs_vid2vid/output/face_forensics
Epoch length: 40
  0% 0/40 [00:00<?, ?it/s]person dict [160.594, 118.24, 0.251877, 192.575, 144.063, 0.824015, 225.618, 146.141, 0.722625, 228.763, 187.411, 0.577983, 222.522, 197.745, 0.0691224, 156.441, 141.995, 0.65878, 136.839, 176.029, 0.816474, 122.349, 203.979, 0.806893, 194.681, 207.035, 0.582138, 219.419, 204.992, 0.580149, 214.285, 253.546, 0.750408, 233.867, 303.093, 0.767982, 172.951, 209.085, 0.521009, 161.562, 260.727, 0.755334, 152.304, 317.576, 0.783057, 0, 0, 0, 161.64, 113.054, 0.485235, 201.904, 119.295, 0.144664, 175.014, 114.108, 0.830086, 109.928, 324.766, 0.654595, 114.095, 326.869, 0.640277, 160.523, 325.834, 0.651386, 214.269, 302.072, 0.6639, 218.372, 302.011, 0.653834, 237.02, 310.333, 0.700539]
person dict [167.8, 86.1641, 0.864743, 120.294, 97.5681, 0.558493, 94.4901, 93.4588, 0.498503, 148.18, 96.528, 0.296182, 163.661, 101.676, 0.0693238, 145.079, 102.756, 0.410478, 200.818, 102.709, 0.455387, 277.273, 103.817, 0.660783, 117.187, 174.002, 0.430313, 99.6447, 175.023, 0.37583, 111.004, 234.891, 0.673355, 102.742, 301.006, 0.74067, 132.683, 174.004, 0.437687, 136.82, 226.63, 0.563235, 128.554, 281.403, 0.770815, 161.654, 76.9165, 0.851908, 169.845, 79.0123, 0.305025, 134.727, 70.7234, 0.842317, 0, 0, 0, 154.368, 287.597, 0.292605, 152.313, 284.509, 0.335124, 121.323, 286.564, 0.595389, 147.154, 313.39, 0.593413, 138.878, 316.507, 0.520831, 94.4743, 307.206, 0.651808]
Training layers:  ['conv_img', 'up', 'weight_generator.fc']
  0% 0/40 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/content/drive/My Drive/imaginaire/inference.py", line 99, in <module>
    main()
  File "/content/drive/My Drive/imaginaire/inference.py", line 95, in main
    trainer.test(test_data_loader, args.output_dir, cfg.inference_args)
  File "/content/drive/My Drive/imaginaire/imaginaire/trainers/fs_vid2vid.py", line 168, in test
    output = self.test_single(data, output_dir, inference_args)
  File "/content/drive/My Drive/imaginaire/imaginaire/trainers/vid2vid.py", line 376, in test_single
    self.finetune(data, inference_args)
  File "/content/drive/My Drive/imaginaire/imaginaire/trainers/fs_vid2vid.py", line 287, in finetune
    self.gen_update(data_finetune)
  File "/content/drive/My Drive/imaginaire/imaginaire/trainers/vid2vid.py", line 265, in gen_update
    self.get_dis_losses(net_D_output)
  File "/content/drive/My Drive/imaginaire/imaginaire/trainers/vid2vid.py", line 642, in get_dis_losses
    if self.last_step_count_D == self.opt_D._step_count:
**AttributeError: 'Adam' object has no attribute '_step_count'**
```

Any help would be appreciated.
Thank you.
