### ISSUE TITLE
Need documentation (second request) for Config File used in Imaginaire FS-Vid2Vid

### ISSUE THREAD

**Issue by grewe** [NVlabs/imaginaire#108]
I was given the following config file to [fix pose fs_vid2vid training.](https://drive.google.com/file/d/1tPVVPL0GxCIT0AmFmy77n66LSbGEfEVm/view?usp=sharing)    I need to know more about the config file and there is zero documentation.

I need to know what all of the hyperparameters mean and what I will need to change and for a base development what I do not need to change.

hyperparams such as` image_save_iter, snapshot_save_epoch, num_epochs_temporal_step, initial_sequence_length,     num_videos_to_test,  num_frames_per_video, batch_size, etc.`

I need to know that given I have different length videos with different resolutions (wxh of image frames) how is this handled --must I do something on my own for pre-processing.

Also num_frames_per_video (is set initially to 10---that seems really low to capture motion).

ALSO given for pose fs_vid2vid you say to use the preprocessing script from the OLD previous repository

**Comment by mingyuliutw** [comment]
We do not plan to provide documentation for the config file as its function is self-explained as one traces the code. The names are also quite meaningful.
