### ISSUE TITLE
FS-Vid2Vid Preprocessing with OpenPose does not create human_instance_maps directory data

### ISSUE THREAD

**Issue by grewe** [NVlabs/imaginaire#109]
How do you create the human_instance_maps data for videos you preprocess for FS_Vid2VId.   There is no documentation.

Have issues with https://github.com/NVlabs/few-shot-vid2vid  [prepocess.py](https://github.com/NVlabs/few-shot-vid2vid/blob/master/data/preprocess/preprocess.py)  and when run the commands for OpenPose, etc. it does not create this directory of data.   Please advise what these are and how to create them.

**Comment by tcwang0509** [comment]
human_instance_maps is a by-product of DensePose. If you're not using DensePose, please also remove human_instance_maps in the config.

**Comment by cantonioupao** [comment]
I agree that there should be more detailed documentation, about the preprocessing of data!
