### ISSUE TITLE
UNIT - pretrained_weight yaml

### ISSUE THREAD

**Issue by IvanGarcia7** [NVlabs/imaginaire#113]
According to the previous implementation of UNIT, when performing the training, the weights were obtained in .pt format, however, in this new implementation, a string appears inside the .yaml file. Would it be possible to make use of the pre-trained models in the previous implementation for this new version?

**Comment by mingyuliutw** [comment]
The network architecture differs slightly. It is not possible to reuse the previous checkpoint.
