### ISSUE TITLE
access to model.

### ISSUE THREAD

**Issue by grewe** [NVlabs/imaginaire#114]
I would like to have access to the pretrained fs vid2vid model (both first version prior imaginaire and later imaginair packaged) pose dance trained model.

You have this available for the face forenics at https://docs.google.com/uc?export=download&id=1F_22ctFmo553nRHy1d_BX7aorc9zk9cF  

Can you please give me the ID for the pt models - for dance pose --again both for original fs vid2vid and for imagiainare-fs_vid2vis?

We are having many problems getting either imaginaire pose or old pose fs_vid2vid working and would like to run inference with our data on your model.  (see issue #113 112 and so on)

Thank you

**Comment by mingyuliutw** [comment]
We do not have plans to release that model.

**Comment by grewe** [comment]
Can you please look at issue 112 --we are doing everything we can to solve
the issue of not being able to run inference without errors.  We supposedly
have a model we trained (hopefully it is okay using your trainer after all
the fixes we made based on issue reports) ---but, can not perform
inference.   Dikshant (grad student) needs to graduate and we are in
desperate to get this accomplished.

Thanks

Lynne

Lynne Grewe |  Professor Computer Science, Director iLab |  California
State University East Bay |
***@***.*** ***@***.***>  *
