### ISSUE TITLE
pre-trained weight url - How to pre-trained UNIT from scratch

### ISSUE THREAD

**Issue by IvanGarcia7** [NVlabs/imaginaire#115]
I want to train a UNIT model from scratch so I followed the tutorial (https://github.com/NVlabs/imaginaire/tree/master/projects/munit).

The steps I have followed are as follows:

1. Generate the structure required in the training for my dataset.
2. Create a yaml file (What value do I have to give to the string named as pretrained_weight?).
3. Execute the command python -m torch.distributed.launch --nproc_per_node=8 train.py \
--config configs/projects/munit/mydataset/ampO1.yaml

When performing the inference to pass the image from one context to another as shown in the tutorial, the following command must be executed:

python -m torch.distributed.launch --nproc_per_node=1 inference.py \
--config configs/projects/unit/mydataset/ampO1.yaml \
--output_dir projects/unit/output/mydataset

My question is, how do you indicate the path of the checkpoint obtained by performing the training from scratch for my dataset?

**Comment by arunmallya** [comment]
Pass in the `--checkpoint <path-to-checkpoint>` argument as described here: https://github.com/NVlabs/imaginaire/blob/master/inference.py#L23-L24
