### ISSUE TITLE
About reconstruct key image in video conferencing

### ISSUE THREAD

**Issue by Vijayue** [NVlabs/imaginaire#116]
Hi, I'm really interested in the application of "One-Shot Free-View Neural Talking-Head Synthesis for Video Conferencing", the video demonstration is impressive!

And I have two questions about reconstructing the key image when new objects are introduced into the video or the person changes.

1. How do we judge whether the current frame needs to transmit residual? What I think of is to calculate some indicators about residual, such as MSE, L1, and AKD, then set a threshold to decide whether transmit the residual. Do you have any suggestions to decide whether the current frame needs to transmit residual?

2. When transmitting the residual to receiver helps to reconstruct the key image, the reconstructed frame will have discontinuities in a video that cannot be ignored, do we have any good solution to solve it?

Thanking you for reading and looking forward to your reply.

**Comment by mingyuliutw** [comment]
@Vijayue 
For 1, I agree that a function predicting the discrepancy between the reconstructed image and the input image will do the job.

For 2, flickering is a common issue for video synthesis methods. We see two pathways moving forward. One is to eliminate transitioning from one source image to another source image. This could be done when the model is exposed to more pose variations during training. The other is to have a temporal smooth function, either applied to the output images or the intermediate features.
