### ISSUE TITLE
Error installing scipy - ERROR: Command errored out with exit status 1

### ISSUE THREAD

**Issue by LongEcho** [NVlabs/imaginaire#118]
Hi,

I get an error when installing Imaginaire with the default version on Linux while the script tries to install scipy. 
Here are the first lines of the error when trying to install:

```
Building wheels for collected packages: scipy, dlib
  Building wheel for scipy (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/eric/anaconda3/bin/python /home/eric/anaconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmptc6hr_xa
       cwd: /tmp/pip-install-3lmgw0fg/scipy_d62a3d751bdc46169da6d01a5a7c7762
  Complete output (640 lines):
  Running from scipy source directory.
  lapack_opt_info:
  lapack_mkl_info:
  customize UnixCCompiler
 
   FOUND:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/home/eric/anaconda3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/usr/local/include', '/usr/include', '/home/eric/anaconda3/include']

    FOUND:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/home/eric/anaconda3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/usr/local/include', '/usr/include', '/home/eric/anaconda3/include']
  /tmp/pip-build-env-u5d7d3sz/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /tmp/pip-build-env-u5d7d3sz/overlay/include/python3.9 is invalid.
    return self.get_paths(self.section, key)
  /tmp/pip-build-env-u5d7d3sz/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /usr/local/include/python3.9 is invalid.
    return self.get_paths(self.section, key)
  /tmp/pip-build-env-u5d7d3sz/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:782: UserWarning: Specified path /usr/include/python3.9 is invalid.
    return self.get_paths(self.section, key)
  Splitting linalg.interpolative Fortran source files
```

After that the error repeats itself. 
The same happens if i'm doing the Windows Installation [Out-dated]. 

I also tried to install SciPy manually but that didn't help.

I am running Ubuntu 20.04 LTS on WSL 2.

What am I doing wrong? 
Thanks!

**Comment by caleb-ross** [comment]
> Hi,
> 
> I get an error when installing Imaginaire with the default version on Linux while the script tries to install scipy. Here are the first lines of the error when trying to install:
> 

Facing similar issues myself while on Ubuntu 18.04 WSL 2 as well, have you managed to negate any of your issues?

**Comment by LongEcho** [comment]
Yeah,
I tried to install it on Windows and the Error didn't show up again. 
It was gone as I installed the Visual Studio C++ Build Tools:
https://www.notion.so/How-To-Install-Microsoft-C-Build-Tools-f79ca6796a524674878b80e998c88b02
Something like CMake should do it on Linux.
I hope it helps!

**Comment by ashish-kubade** [comment]
@LongEcho were you able to run architectures in this repo, e.g GANCraft, successfully with Ubuntu 20.04?
