### ISSUE TITLE
COCO-Stuff edge maps

### ISSUE THREAD

**Issue by PeterouZh** [NVlabs/imaginaire#12]
Thank you very much for the awesome library!

I want to know how to get the edge maps of COCO-Stuff for training SPADE. Currently, I only have COCO training images, COCO validation images, and seg_maps from stuffthingmaps_trainval2017.

**Comment by mingyuliutw** [comment]
The edge map can be computed by unioning the edge map of the coco-stuff segmentation mask and the edge map of the instance segmentation map.
