### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by leoShen917** [NVlabs/imaginaire#127]
Hi， when i run the code 'python -m torch.distributed.launch --nproc_per_node=3 train.py –config configs/projects/spade/cocostuff/base128_bs4.yaml --logdir logs/projects/spade/cocostuff/base128_bs4.yaml'
And the trained dataset and the val dataset are into LMDB format based on
for f in train val; do
python scripts/build_lmdb.py \
--config configs/projects/spade/cocostuff/base128_bs4.yaml \
--data_root "/data0/shenliao/imaginaire/cocostuff_raw/${f}" \
--output_root "/data0/shenliao/imaginaire/dataset/cocostuff/${f}" \
--overwrite \
--paired
done
During training, the error is :
No checkpoint found.
Epoch 0 ...
Traceback (most recent call last):
  File "/home/shenliao/workspace/imaginaire-master/train.py", line 167, in <module>
    main()
  File "/home/shenliao/workspace/imaginaire-master/train.py", line 161, in main
    trainer.end_of_epoch(data, current_epoch, current_iteration)
UnboundLocalError: local variable 'data' referenced before assignment

**Comment by cdmc-zrz** [comment]
Hello, I also encountered this problem, can you tell me how you solved it?

**Comment by cdmc-zrz** [comment]
Looking forward to your reply, if you can see this message

**Comment by yc-cui** [comment]
Maybe the number of total images is less than batch size.
