### ISSUE TITLE
<fs-v2v> Did anyone successfully run the 'pose' training codes in the repo?

### ISSUE THREAD

**Issue by eastchun** [NVlabs/imaginaire#128]
I have downloaded the fs-v2v codes and ran the simple 'pose' training dataset (2 video sequences and 8 frames each) using single GPU (train_g1).

After 3500 iterations in epoch 1, the training became unstable (GAN_feat/Gf_GAN_feat suddenly soared up and D_real/D_fake became almost zeros) and synthesized image became all white (sometimes all black).

![results](https://user-images.githubusercontent.com/29370319/154828948-a6d57904-aecd-4e8a-9947-c8a6e19613f9.jpg)

I tried again and again by increasing GPUs to 2 or 4. But still got the same result, getting either all black or all white synthesized images  from around iteration 3000 ~ 4000 in epoch 1. Sometimes, I continued training epochs hoping that this might be a transient behavior. But, still got the same all black or all white synthesized images all the way up to epoch 20.

**Comment by Mumuwei** [comment]
How about the quality of your final generated image?

**Comment by songyn95** [comment]
@eastchun  @Mumuwei  @tmbdev  @bkhailany  @arunmallya 
I have also found this problem now. After 14/70 iterations, the synthesized images are all black.I use a street  datasets. What is the reason for this? Is it because there are too few datasets?
