### ISSUE TITLE
dancing datasets#lmdb

### ISSUE THREAD

**Issue by Mumuwei** [NVlabs/imaginaire#135]
I have processed the data to lmdb format, the location is _datasets/youtubeDancing/lmdb/train_, and the roots in ampO1.yaml is also _datasets/youtubeDancing/lmdb/train_. But during training, the following occurs

_Found 0 sequences
Found 0 files
Folder at datasets/youtubeDancing/lmdb/train/images opened.
Folder at datasets/youtubeDancing/lmdb/train/pose_maps-densepose opened.
Folder at datasets/youtubeDancing/lmdb/train/poses-openpose opened.
Folder at datasets/youtubeDancing/lmdb/train/human_instance_maps opened._

Hope someone can help, thanks
![image](https://user-images.githubusercontent.com/44329935/157008738-52d22b61-40a5-4bf5-b2d0-ffb8434a9039.png)

**Comment by Zzzzzzzzzzz1** [comment]
I also encountered the same problem, it seems to be related to the loading of lmdb

**Comment by Mumuwei** [comment]
> I also encountered the same problem, it seems to be related to the loading of lmdb

Do you know how to solve it?

**Comment by tcwang0509** [comment]
It means your lmdb is in a different format than expected. Please double check it's in the same structure and file extensions as the provided example.

**Comment by cdmc-zrz** [comment]
Can you please tell me what each of these columns means?





------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Ting-Chun ***@***.***&gt;;
Send time:&nbsp;Wednesday, Mar 16, 2022 0:49 AM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [NVlabs/imaginaire] dancing datasets#lmdb (Issue #135)





 
Closed #135.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Mumuwei** [comment]
> Can you please tell me what each of these columns means?
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: &nbsp;"Ting-Chun ***@***.***&gt;; Send time:&nbsp;Wednesday, Mar 16, 2022 0:49 AM ***@***.***&gt;; ***@***.***&gt;; ***@***.***&gt;; Subject: &nbsp;Re: [NVlabs/imaginaire] dancing datasets#lmdb (Issue #135) Closed #135. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

I tried not to use lmdb data, but to use raw data directly, there is no problem.

**Comment by moulimatsa** [comment]
Hi @Mumuwei 

Do you have any problem with checkpoint saving after certain epochs( my case 5 epochs). I couldn't find saved checkpoints in my log directory after 10 epochs.

**Comment by Mumuwei** [comment]
> Do you have any problem with checkpoint saving after certain epochs( my case 5 epochs). I couldn't find saved checkpoints in my log directory after 10 epochs.

I also had a similar problem, in my case no model checkpoint was saved, I modified the code in _train.py_ directly for simplicity

**Comment by moulimatsa** [comment]
Hi @Mumuwei 

My problem looks similar. can you help me with what exactly you have modified to save the checkpoint.

**Comment by Mumuwei** [comment]
> Hi @Mumuwei
> 
> My problem looks similar. can you help me with what exactly you have modified to save the checkpoint.

<img width="510" alt="Snipaste_2022-03-24_17-43-54" src="https://user-images.githubusercontent.com/44329935/159888627-546448d3-8993-49a2-a539-d0afc3c03b08.png">
Modify the code as needed, but I'm not sure if this is the right way to do it. And my test results are not good, it may be related to my dataset, if you can get satisfactory results, can you contact me, my email is _yangquanwei@mail.ustc.edu.cn_
