### ISSUE TITLE
Generation of face edges for fs_vid2vid

### ISSUE THREAD

**Issue by AlexMeinke** [NVlabs/imaginaire#136]
For the fs_vid2vid model the documentation simply has this vague sentence about how to generate the face edges from the keypoints:
"We then use a landmark detection method (e.g. dlib) to estimate the face keypoints, and interpolate them to get face edges."
The old repository and the paper also do not go into detail about this, as far as I can tell.

Is the code for this available, or at least more precise instructions?

**Comment by mingyuliutw** [comment]
Follow this line
https://github.com/NVlabs/imaginaire/blob/c6f74845c699c58975fd12b778c375b72eb00e8d/configs/projects/fs_vid2vid/face_forensics/ampO1.yaml#L152
