### ISSUE TITLE
Does fs_vid2vid have a finetune method?

### ISSUE THREAD

**Issue by cdmc-zrz** [NVlabs/imaginaire#137]
A full fs_vid2vid takes too long to train, I want to finetune this model by training some of the layers to add some side face information, but I don't know how to do it?

**Comment by mingyuliutw** [comment]
For talking-head, I assume fine-tuning from the voxel-celebrity model might work.
For full-body, I assume fine-tuning from the youtube dancing model might work

**Comment by cdmc-zrz** [comment]
> For talking-head, I assume fine-tuning from the voxel-celebrity model might work. For full-body, I assume fine-tuning from the youtube dancing model might work

https://github.com/NVlabs/imaginaire/issues/135   Is there a solution to this problem in fs_vid2vid, there has been a problem loading data according to the process
