### ISSUE TITLE
Error when running on Win10

### ISSUE THREAD

**Issue by tigerccx** [NVlabs/imaginaire#14]
I set up the environment and tried to run pix2pixHD inferring. But with this commend line: 

`python inference.py --single_gpu --config "configs/projects/pix2pixhd/cityscapes/ampO1.yaml" --output_dir "projects/pix2pixhd/output/cityscapes" --checkpoint "../models/cityscapes_1k.pt"`

I got the following runtime error: 

`Traceback (most recent call last):
  File "inference.py", line 91, in <module>
    main()
  File "inference.py", line 39, in main
    set_affinity(args.local_rank)
  File "D:\Sources\Download\imaginaire-master\imaginaire-master\imaginaire\utils\gpu_affinity.py", line 57, in set_affinity
    os.sched_setaffinity(0, dev.getCpuAffinity())
AttributeError: module 'os' has no attribute 'sched_setaffinity'`

Is there any way to get around this?

**Comment by arunmallya** [comment]
Could you try commenting that line and see if it works?

**Comment by tigerccx** [comment]
> Could you try commenting that line and see if it works?

That should probably have worked. I was able to get through that part of code. But I ran into a new error about apex. 

`Traceback (most recent call last):
  File "inference.py", line 91, in <module>
    main()
  File "inference.py", line 64, in main
    get_model_optimizer_and_scheduler(cfg, seed=args.seed)
  File "D:\Sources\Download\imaginaire-master\imaginaire-master\imaginaire\utils\trainer.py", line 115, in get_model_optimizer_and_scheduler
    opt_G = get_optimizer(cfg.gen_opt, net_G)
  File "D:\Sources\Download\imaginaire-master\imaginaire-master\imaginaire\utils\trainer.py", line 257, in get_optimizer
    return get_optimizer_for_params(cfg_opt, params)
  File "D:\Sources\Download\imaginaire-master\imaginaire-master\imaginaire\utils\trainer.py", line 276, in get_optimizer_for_params
    betas=(cfg_opt.adam_beta1, cfg_opt.adam_beta2))
  File "D:\Programs\Anaconda\envs\Imaginaire\lib\site-packages\apex\optimizers\fused_adam.py", line 79, in __init__
    raise RuntimeError('apex.optimizers.FusedAdam requires cuda extensions')
RuntimeError: apex.optimizers.FusedAdam requires cuda extensions`

It seems to be an error concerning apex installation. I was not able to build and install apex with CUDA/C++ extension successfully on my Win10 so I only installed apex without that. So can I avoid invoking the part of apex requiring CUDA/C++ extension somehow?

**Comment by plutoyuxie** [comment]
Hi, I just run fs_vid2vid inferring successfully. I met the same error as you did on Win10, here is my solution:
Change the config file, adding fused_opt: False here:
# Optimization option.
gen_opt:
    type: adam
    fused_opt: False
    ......
dis_opt:
    type: adam
    fused_opt: False
    ......

Besides, maybe the installation of those third_party packages is missing in install.bat. 
And I have installed channelnorm/correlation/flow_net/resample2d packages manually, refering to commands in install.sh

**Comment by tigerccx** [comment]
> Hi, I just run fs_vid2vid inferring successfully. I met the same error as you did on Win10, here is my solution:
> Change the config file, adding `fused_opt: False` here:
> 
> ```
> # Optimization option.
> gen_opt:
>     type: adam
>     fused_opt: False
>     ......
> dis_opt:
>     type: adam
>     fused_opt: False
>     ......
> ```
> 
> Besides, maybe the installation of those third_party packages is missing in install.bat.
> And I have installed channelnorm/correlation/resample2d packages manually, referring to commands in install.sh.

This works! Thanks a lot!
