### ISSUE TITLE
How content-conditioned style encoder is implemented? 

### ISSUE THREAD

**Issue by lichong952012** [NVlabs/imaginaire#144]
How the elementwise product is implemented between style encoder and content encoder in COCO-FUNIT?  It looks the same as FUNIT.
![image](https://user-images.githubusercontent.com/34733623/163348762-3c4722f6-11bd-48d3-8404-dfc27d3d6739.png)

**Comment by mingyuliutw** [comment]
In FUNIT, the style code depends on the style image only. The upper branch of the figure is absent. Of course, we do not use constant style bias in FUNIT.
