### ISSUE TITLE
No module named 'upfirdn2d_cuda'

### ISSUE THREAD

**Issue by yangwenbing2** [NVlabs/imaginaire#145]
when i run 
`python -m torch.distributed.launch --nproc_per_node=8 train.py --config configs/projects/munit/afhq_dog2cat/ampO1.yaml`

the error raise.

my enviroment:
cuda: 10.2
pytorch:1.7
python:3.6

**Comment by mingyuliutw** [comment]
upfirdn2d_cuda will be compiled when you run scripts/install.sh
