### ISSUE TITLE
How to run fs_vid2vid?

### ISSUE THREAD

**Issue by 0x123456789** [NVlabs/imaginaire#15]
Sorry, may be it is obvious but can you give some explanation how to run it?
As I understand if I have my video with face I should convert it to face keypoints via dlib. But what the next step? 
Can you please write some commands how to run this network when I want to give my video as an input
Thanks!

**Comment by mingyuliutw** [comment]
We have a README for doing training and inference with few-shot vid2vid

https://github.com/NVlabs/imaginaire/tree/master/projects/fs_vid2vid

Could you take a look to see if the information helps?
