### ISSUE TITLE
wc_vid2vid: FileNotFoundError: [Errno 2] /mnt/bigdata01/datasets/wc_vid2vid/cityscapes/train/lmdb

### ISSUE THREAD

**Issue by Skyrelixa** [NVlabs/imaginaire#155]
Hello! Thank you for your hard work in making this repository of open source code available for researchers. 

I'm in the training stage for wc_vid2vid using the cityscapes dataset. I've formatted the data appropriately, successfully created the LMDB format for training, and then ran: 
`python -m torch.distributed.launch --nproc_per_node=1 train.py --config configs/projects/wc_vid2vid/cityscapes/seg_ampO1.yaml`

However, I'm encountering the following runtime error:
`/home/ubuntu/avatar/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Using random seed 2
Training with 1 GPUs.
Make folder logs/2022_0708_1540_06_seg_ampO1
cudnn benchmark: True
cudnn deterministic: False
Creating metadata
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    main()
  File "train.py", line 89, in main
    train_data_loader, val_data_loader = get_train_and_val_dataloader(cfg, args.seed)
  File "/home/ubuntu/avatar/imaginaire/imaginaire/utils/dataset.py", line 80, in get_train_and_val_dataloader
    train_dataset, val_dataset = _get_train_and_val_dataset_objects(cfg)
  File "/home/ubuntu/avatar/imaginaire/imaginaire/utils/dataset.py", line 25, in _get_train_and_val_dataset_objects
    train_dataset = dataset_module.Dataset(cfg, is_inference=False)
  File "/home/ubuntu/avatar/imaginaire/imaginaire/datasets/paired_videos.py", line 37, in __init__
    super(Dataset, self).__init__(cfg, is_inference, is_test)
  File "/home/ubuntu/avatar/imaginaire/imaginaire/datasets/base.py", line 95, in __init__
    filenames, metadata = create_metadata(
  File "/home/ubuntu/avatar/imaginaire/imaginaire/utils/lmdb.py", line 148, in create_metadata
    available_data_types = path.get_immediate_subdirectories(data_root)
  File "/home/ubuntu/avatar/imaginaire/imaginaire/utils/path.py", line 19, in get_immediate_subdirectories
    return sorted([name for name in os.listdir(input_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/bigdata01/datasets/wc_vid2vid/cityscapes/train/lmdb'
`
Are there any ideas as to what is causing this error? I am currently working in a python3.8-venv because of updated dependencies (PyTorch). And if it's as simple as changing the path for the directory, where and how do I change the path?

Any reply will be much appreciated!

**Comment by digvijayad** [comment]
@Skyrelixa Update this file `configs/projects/wc_vid2vid/cityscapes/seg_ampO1.yaml` with the actual location of your lmdb files.

**Comment by Skyrelixa** [comment]
@digvijayad Thank you! This works perfectly. Closing the issue.
