### ISSUE TITLE
Perceptual Loss used for MUNIT not using Instance Normalization for content comparison only

### ISSUE THREAD

**Issue by theponpon** [NVlabs/imaginaire#16]
Hi there,

If I understood correctly the original MUNIT article/implementation, the vgg loss was doing an additional Instance normalization to "remove" Style from the input image.
In the imaginaire implementation, the PerceptualLoss referenced in the MUNIT trainer seems to be the original perception loss, without any Instance normalization.

Am I missing something?
If this is correct, does it still make sense to call the vgg loss in addition to the others for MUNIT?

Thank you in advance,

Pierre

**Comment by xunhuang1995** [comment]
Fixed. Thanks for catching this.
