### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by ashish-kubade** [NVlabs/imaginaire#162]
Can this project be run with Ubuntu 20.04 or 22.04?
I am getting errors with 20.04 and running short on deadlines. So, I need to decide if I should roll back my os to 18.04 or correct my environment on 20.04 itself.
TIA.

**Comment by ashish-kubade** [comment]
I am able to run on Ubuntu 20.04.

**Comment by XuanHien304** [comment]
Can I ask how to set up install and train MUNIT model? I do following the instruction but get many errors
