### ISSUE TITLE
How to keep the content unchanged and only change the style?

### ISSUE THREAD

**Issue by xiaowenhe** [NVlabs/imaginaire#20]
Hi, thanks for your great work!
I have a question that how to keep the content unchanged and only change the style? In paper, you show result about  Summer ↔ winter, like this, the content is unchanged and style change.  
But when I train with other datasets, I can not keep the content unchanged. 
For example, 
![image](https://user-images.githubusercontent.com/28335784/96809025-a8faa280-144c-11eb-983a-d104761a1d36.png)

The left is input , right is generate by code. But the content is change from left to right?

So, how can I can keep the content unchange?

Thank you!

**Comment by xiaowenhe** [comment]
My datasets like:
![image](https://user-images.githubusercontent.com/28335784/96809893-fdeae880-144d-11eb-9110-310910a1b339.png)

left is trainA, right is trainB. And I use the tf code:https://github.com/taki0112/MUNIT-Tensorflow.

**Comment by xunhuang1995** [comment]
It is worthwhile to try increasing the weight of cycle consistency loss/perceptual loss/content reconstruction loss. All of them are useful for preserving content information.
