### ISSUE TITLE
fs_vid2vid pose model - youtube playlist 3

### ISSUE THREAD

**Issue by kaswani29** [NVlabs/imaginaire#21]
Third youtube plaliyst [link](https://www.youtube.com/playlist?list=PLsVSF-hJhvBKV9XDaqJAEx-otHG1_XT9q) has more than 90% videos with multiple people in single frame will that affect the model performance or does it help model generalize ?

Just wondering how does model learn from so much noise vs important data.

**Comment by mingyuliutw** [comment]
You need to apply human detection and tracking to obtain video clips contain a single person.

Facebook's detection is a good repo for this task.
