### ISSUE TITLE
数据集下载

### ISSUE THREAD

**Issue by xuhui1994** [NVlabs/imaginaire#23]
Thanks for your work for image enhancement ! I have tried to download these datasets in the paper. But in the  halfway I always encounter a networks issue . Could you provide a baiduyun links or others ! Thanks again！！！

**Comment by mingyuliutw** [comment]
Haven't use a BAIDU drive before. Could you share some pointers? How to download files from Baidu drive using python code?

**Comment by ZhouYuanlin** [comment]
我登录Dropbox的数据集链接显示404，国内找到了一个备份的下载了。

数据集名称：AFHQ - 动物脸部数据集-StarGAN v2图片融合数据集
数据集链接：https://aistudio.baidu.com/aistudio/datasetdetail/47301
数据集简介：StarGAN v2图片风格融合数据集 动物脸部数据集Animal Faces-HQ（AFHQ），该数据集包含512×512分辨率的15,000张高质量图像。 上图显示了AFHQ数据集的示例图像。 数据集包括猫，狗和野生动物的三份，每份提供约5000张图像。
参考：https://github.com/clovaai/stargan-v2

**Comment by mingyuliutw** [comment]
AFHQ is not the dataset we use. We are using a subset of images from the ImageNet dataset.
