### ISSUE TITLE
Plan to add "Panoptic-based Image Synthesis"?

### ISSUE THREAD

**Issue by sangwoomo** [NVlabs/imaginaire#26]
Hi, thank you for a great repository!

I recently read ["Panoptic-based Image Synthesis"](https://arxiv.org/abs/2004.10289) (CVPR 2020) from NVIDIA team, which improves SPADE with additional panoptic segmentation labels. Do you have any plan to add this model to the official imaginaire repository?

**Comment by mingyuliutw** [comment]
Sorry. This is not in our plan. The SPADE model released in this repo achieves an FID of 18-19 in the COCO dataset, which seem to be better than recent vision publication results.
