### ISSUE TITLE
UNIT implementation

### ISSUE THREAD

**Issue by ds2268** [NVlabs/imaginaire#27]
First of all, thank you for this great library.

I was checking the UNIT implementation and saw that it differs from the original paper at least in 2 things:

- Spatial AE is used instead of VAE (L1 instead of KL loss)
- There is no weight sharing in E and G layers
- Cycle reconstruction is probably implemented differently and probably also the reason for not needing weight sharing (assumption, as I haven't checked original UNIT implementation)

Can you give us a bit more of the reasoning and describe any other major changes that might be there and I didn't notice?

Thanks!

**Comment by mingyuliutw** [comment]
From my perspective, the key thing in the UNIT paper is the shared-latent space idea. VAE and Spatial AE are two different implementations.

Weight-sharing for E and G is still useful for challenging cases as it allows you to use your inductive bias to help with the training. I was kind of lazy and didn't implement a version that one can support a wide range of weight-sharing scheme using based on the yaml file.

- Shared-latent space implies cycle-consistency.
- Weight-sharing limits the solution space of the encoder and decoder. It is a different regularization to the cycle consistency.
