### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by hstern2** [NVlabs/imaginaire#28]
I ran the install.sh script and it completed successfully, however when I try test_training.sh I get RuntimeError: CUDA error: no kernel image is available for execution on the device.  Thanks for any suggestions

[try.log](https://github.com/NVlabs/imaginaire/files/5524645/try.log)

**Comment by xunhuang1995** [comment]
It's probably due to GPU/CUDA incompatibility and is not specific to this repository. Check other threads like https://github.com/facebookresearch/detectron2/issues/235 https://github.com/pytorch/pytorch/issues/31285
