### ISSUE TITLE
"unauthorized: authentication required" from ./scripts/build_docker.sh

### ISSUE THREAD

**Issue by calvinpelletier** [NVlabs/imaginaire#3]
> Sending build context to Docker daemon   1.35MB
> Step 1/22 : FROM nvcr.io/nvidian/pytorch:20.07-py3
> unauthorized: authentication required

Is "nvidian" a typo? It works fine when I switch it to "nvidia".

**Comment by xunhuang1995** [comment]
Just changed it to "nvidia". Thanks!
