### ISSUE TITLE
HELP! expected scalar type Half but found Float

### ISSUE THREAD

**Issue by vantony1** [NVlabs/imaginaire#33]
Hi, 

I ran install.sh and then tries running the test script but this is the error I am getting. I have been struggling with getting this library working for more than three weeks now and have fixed multiple issues through long stackoverflow and github searched. Please any assistance would be very helpful.

[try-i.log](https://github.com/NVlabs/imaginaire/files/5561201/try-i.log)

RuntimeError: expected scalar type Half but found Float

**Comment by mingyuliutw** [comment]
Could you share your machine configuration?
Ubuntu 16.04?
CUDA XXX?
and which script are you running.

**Comment by mingyuliutw** [comment]
Since to be same issue with #34

**Comment by vantony1** [comment]
Hello, we are running test_training.sh on RHEL 7.6, CUDA 10.2

**Comment by vantony1** [comment]
Hello, can someone please help me with this? I would really appreciate it! Our research has been roadblocked by not being able to run imaginaire
