### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by AidanGoldfarb** [NVlabs/imaginaire#34]
I ran install.sh and then tried running the test script but this is the error I am getting. I have been struggling with getting this library working for more than three weeks now and have fixed multiple issues through long stackoverflow and github searched. Please any assistance would be very helpful.

[try-i.log](https://github.com/NVlabs/imaginaire/files/5561323/try-i.log)

**Comment by mingyuliutw** [comment]
It looks like you are hitting an issue with the ampO1 with pix2pixHD demo code.

Were you able to run scripts/test_train.sh
