### ISSUE TITLE
Is local enhancer supported in imaginaire's implementation of pix2pixHD?

### ISSUE THREAD

**Issue by kondela** [NVlabs/imaginaire#35]
Hello, I've noticed that in pix2pixHD config for cityscapes it appears, based on the following lines:
https://github.com/NVlabs/imaginaire/blob/7828f78924e7a5a4313bfe3c2460a59adfb2d8e3/configs/projects/pix2pixHD/cityscapes/ampO1.yaml#L40-L42

that you only use global generator instead of global generator + local enhancer. Is this intended behavior, or is it specific to cityscapes config? Does the current imaginaire's implementation of pix2pixHD support training global generator and local enhancer as in the original implementation? If so, could you recommend what a config should look like in that case?

**Comment by tcwang0509** [comment]
It is not used for training 1k images. It is only used for training 2k resolution images, where the num_enhancers should be set to 1.
