### ISSUE TITLE
Hope to support CUDA11 as soon as possible

### ISSUE THREAD

**Issue by Y-P-Zhang** [NVlabs/imaginaire#36]
It appears that Apex's configuration is incompatible with CUDA11.

**Comment by Y-P-Zhang** [comment]
It appears that Apex's configuration is incompatible with CUDA11.

**Comment by JohnHardline** [comment]
Same for me! It's really hard to install this lib on normal Ubuntu System due to Cuda 10.2 dependency!

**Comment by zhwhong** [comment]
> It appears that Apex's configuration is incompatible with CUDA11.

I have the same problem. The apex package cannot be installed on CUDA 11.1 (RTX 3090). Any suggestions?

**Comment by zhwhong** [comment]
There is a solution to refer.

https://github.com/NVIDIA/apex/issues/988#issuecomment-726343453
