### ISSUE TITLE
fs-vid2vid YouTube dancing pretrained weights

### ISSUE THREAD

**Issue by tebin** [NVlabs/imaginaire#4]
Hi, it is my understanding that both FaceForensics and YouTube dancing share the same pretrained weights. However when I run 
```bash
python inference.py --single_gpu --num_workers 0 \
--config configs/projects/fs_vid2vid/YouTubeDancing/ampO1.yaml \
--output_dir projects/fs_vid2vid/output/YouTubeDancing \
--checkpoint epoch_00200_iteration_000005800_checkpoint.pt
```
I get a bunch of key mismatches like `Missing key(s) in state_dict: "module.weight_generator.ref_img_first.layers.conv.weight_orig"` and `Unexpected key(s) in state_dict: "module.num_updates_tracked"` to name a few.

**Comment by tcwang0509** [comment]
The two datasets have different pretrained weights. Unfortunately we're not allowed to release the model for YouTube dancing as per the company policy. Thank you for your understanding.

**Comment by NoamGaash** [comment]
@tcwang0509
may it be possible to release the weights for academic-only puposes?
I'm having difficulities to reproduce the results on my workstation
