### ISSUE TITLE
Questions about length of pytorch training dataset in fs_vid2vid.

### ISSUE THREAD

**Issue by DaddyJin** [NVlabs/imaginaire#45]
I want to run the fs_vid2vid. I prepare 5 videos for training and 1 video for val, extract their frames and get corresponding landmarks saved in the json file.  And I preprocess them into lmdb format.

**Question 1**
However, when I run the fs_vid2vid program using my tiny dataset, I found that the  length of traing dataset is 2 and the length of corresponding training dataloader is 0, which throws an error.

Could someone help me solve this problem?

**Question 2**
Here is the length information of my dataset. What is the detailed meaning of **Num datasets, Num sequences, Max sequence length and Epoch length**?
![image](https://user-images.githubusercontent.com/22629481/103339060-5a582d00-4abb-11eb-90b1-bab1aa735b60.png)

**Comment by arunmallya** [comment]
Seems like your training dataset has only 2 videos of max 5 frames each.
Further, your val set has 2 videos of max 1 frame each, which obviously violates the requirement of seq_len + few_shot_k > max_seq_len. 
I would suggest taking a look at the sample dataset provided with the method. You can run `python ./scripts/download_test_data.py --model_name fs_vid2vid` to download it.

**Comment by DaddyJin** [comment]
Thank you for your kindly reply. @arunmallya 
I found it's because I missed the **--paired** argument when preprocessing data into LMDB format.
Could you explain detailedly about the **--paired** argument?
Thx!

**Comment by arunmallya** [comment]
Paired means that for the same filename, there exist multiple data types, e.g. images, seg_maps, etc. in this format:
```
images/
    00.jpg
    01.jpg
seg_maps/
    00.png
    01.png
```

Unpaired means that there are two data types with no matching filenames, as is used in UNIT
```
domain_a/
    00.jpg
    01.jpg
domain_b/
    aa.jpg
    xx.jpg
```

Each of these uses a different format for the `metadata.json` dumped in the dataset.
Paired only needs to store the relative filenames once, while unpaired needs to store the full path for every file.

**Comment by DaddyJin** [comment]
Appreciate it.
It really helps!
Thx for the great work.
