### ISSUE TITLE
Seek for the test dataset for COCO-FUNIT

### ISSUE THREAD

**Issue by zhwhong** [NVlabs/imaginaire#46]
In the COCO-FUNIT paper, the model was tested on four datasets, Carnivores, Mammals, Birds, and Motorbikes. However, in this repository, only the animal faces dataset(Carnivores) was available. So can you share the other three test datasets(Mammals, Birds, and Motorbikes)? It would help us a lot. Thanks.

Best regards.

**Comment by mingyuliutw** [comment]
We do not have plans to release Carnivores, Mammals, Birds, and Motorbikes datasets. However, such datasets can be easily collected with Google Image Search.
