### ISSUE TITLE
wc_vid2vid unprojection scripts

### ISSUE THREAD

**Issue by Ma-Stan** [NVlabs/imaginaire#5]
Will the SfM/generation of unprojections code be released soon?

**Comment by mingyuliutw** [comment]
@arunmallya

**Comment by arunmallya** [comment]
I will try to post the instructions by the end of the month. 
The basic steps are as follows:
- Run OpenSfM on ground truth images and get list of 3D points
- For every image, find the mapping of pixel (x, y) to 3D point id.

The unprojections are basically a list of [x, y, 3D point id], so that we know which 3D point is used to color which image pixel.

**Comment by arunmallya** [comment]
Please run SfM on your image collection using [OpenSfM](https://github.com/mapillary/OpenSfM) and then run the attached script to obtain unprojections required by `wc_vid2vid`.
[unprojections.zip](https://github.com/NVlabs/imaginaire/files/5471693/unprojections.zip)

**Comment by k-eak** [comment]
Hi @arunmallya, thank you for the detailed explanation. Could you also comment on the configurations, you've used for OpenSfM. It seems like, running with the default configuration, the feature matching takes too long due to a large number of images.

**Comment by arunmallya** [comment]
Hi, you can have a look at https://github.com/mapillary/OpenSfM/pull/133 to speed up matching on a video.
Setting `matching_order_neighbors: 2` will greatly speed up matching as it will only compare features from consecutive frames of a video, based on image name.
Note that you have to name your frames such that they correspond to time when arranged alphabetically.

**Comment by alamayreh** [comment]
> Please run SfM on your image collection using [OpenSfM](https://github.com/mapillary/OpenSfM) and then run the attached script to obtain unprojections required by `wc_vid2vid`.
> [unprojections.zip](https://github.com/NVlabs/imaginaire/files/5471693/unprojections.zip)

Hi, I'm trying to run the scirpt to optain the unprojections, but I'm getting this error 


Importing ply file
RPly: Unable to open file
```
[Open3D WARNING] Read PLY failed: unable to open file: sfm_dir=/home/omran/Desktop/prepare_WC/example/stuttgart_00_00/undistorted/depthmaps/merged.ply
Imported in 0.00014519691467285156 seconds
Found 0 points
Traceback (most recent call last):
  File "/home/omran/Desktop/prepare_WC/unprojections/release/project_keypoints_cuda.py", line 231, in <module>
    main(args.image_dir, args.sfm_dir, args.save_dir,
  File "/home/omran/Desktop/prepare_WC/unprojections/release/project_keypoints_cuda.py", line 75, in main
    ds = dataset.DataSet(image_dir, sfm_dir)
TypeError: __init__() takes 2 positional arguments but 3 were given
```

**Comment by cdapo** [comment]
Hi,

I'm getting an error using the unprojections script:
`points_cuda.py
Importing ply file
Imported in 0.22571182250976562 seconds
Found 238756 points
  0%|                                                     | 0/3 [00:00<?, ?it/s]Transform took: 0.004827976226806641

Traceback (most recent call last):
  File "project_keypoints_cuda.py", line 225, in <module>
    main(image_dir, sfm_dir, save_dir,
  File "project_keypoints_cuda.py", line 107, in main
    rgb = rgb_all[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
`

Any idea how to fix this?

**Comment by digvijayad** [comment]
@cdapo Were you able to resolve the error? I'm receiving the same error.
