### ISSUE TITLE
Windows : Resample2d_CUDA DLL Load failed

### ISSUE THREAD

**Issue by crenaudineau1** [NVlabs/imaginaire#50]
Hello,

My config : 
conda install python=3.6
conda install pytorch==1.4.0 torchvision==0.5.0 cudatoolkit=10.1 -c pytorch
Windows 10
RTX 2080 TI

I have sucessfull installed all dependence but when I test an inference (vid2vid), I have this error : 

`   import resample2d
  File "D:\imaginaire\venv\lib\site-packages\resample2d_cuda-0.0.0-py3.6-win-amd64.egg\resample2d.py", line 4, in <module>
    import resample2d_cuda
ImportError: DLL load failed: Le module spécifié est introuvable.`

I have sucessfull installed third party with : 
`   
python setup.py install
creating d:\imaginaire\venv\lib\site-packages\resample2d_cuda-0.0.0-py3.6-win-amd64.egg
Extracting resample2d_cuda-0.0.0-py3.6-win-amd64.egg to d:\imaginaire\venv\lib\site-packages
resample2d-cuda 0.0.0 is already the active version in easy-install.pth

Installed d:\imaginaire\venv\lib\site-packages\resample2d_cuda-0.0.0-py3.6-win-amd64.egg
Processing dependencies for resample2d-cuda==0.0.0
Finished processing dependencies for resample2d-cuda==0.0.0`

Thanks for your feedback on Windows install.

Thanks.

**Comment by mingyuliutw** [comment]
The recent update should fix the issue. If not, please reopen the issue. We do not train any models using Windows. Support is pretty limited for Windows.
