### ISSUE TITLE
How to build docker image on centos 7?

### ISSUE THREAD

**Issue by EvanLavizadeh** [NVlabs/imaginaire#51]
Hello!

I cannot build from source because I don't have sudo permissions so I can't install many of the dependencies. 
My first question is, do you still need the prerequisites (Anaconda3, cuda10.2, cudnn) if you want to build and run on docker?

Secondly, since the dockerfile uses apt-get, and Centos doesn't use apt, does anyone have any recommendations for how I can build? Not all of these packages are available on yum and without sudo, building these dependencies from source is a huge pain.

The build fails because my machine doesn't have access to apt
`/bin/sh: apt-get: not found`

**Comment by mingyuliutw** [comment]
As mentioned in [installation-guide](https://github.com/NVlabs/imaginaire/blob/master/INSTALL.md#installation-guide), the library was developed on Ubuntu. We don't really use Centos and would not be able to answer your questions.
