### ISSUE TITLE
Training on custom dataset with different image resolution

### ISSUE THREAD

**Issue by GauravBh1010tt** [NVlabs/imaginaire#52]
Hi,

Is it possible to train the models (munit) on image size 64\*64 or 128\*128?

**Comment by arunmallya** [comment]
Yes. You will have to adjust the generator and discriminator to work with the chosen image sizes.

You should be able to do that by adjusting params here: https://github.com/NVlabs/imaginaire/blob/master/configs/projects/munit/edges2shoes/ampO1.yaml#L52-L73

You will also have to tell the dataloader to perform appropriate resizing/cropping:
https://github.com/NVlabs/imaginaire/blob/master/configs/projects/munit/edges2shoes/ampO1.yaml#L104-L128
