### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by arulpraveent** [NVlabs/imaginaire#55]
@mingyuliutw We created lmdb dataset for few shot vid2vid from our custom dataset while we started the training script we got an error like "UnboundLocalError: local variable 'data' referenced before assignment" we made sure that all the file names are same in the dataset folders what could be the reason for this?

**Comment by arunmallya** [comment]
Could you please post the entire stack trace? Can't diagnose the issue with the information provided.

**Comment by arulpraveent** [comment]
@arunmallya Sure the command that i used to create the lmbd dataset is "python3 scripts/build_lmdb.py --config configs/projects/fs_vid2vid/YouTubeDancing/ampO1.yaml --data_root /mnt/fs/datasets/fsv/jay-arul-long-shot-fsv/train --output_root ~/imaginaire/datasets/youtubeDancing/lmdb/train --paired"
The command that I used to start the training is "python3 -m torch.distributed.launch --nproc_per_node=1 train.py --single_gpu --config configs/projects/fs_vid2vid/YouTubeDancing/ampO1.yaml"
The stack trace of the error is
Traceback (most recent call last):
  File "train.py", line 93, in <module>
    main()
  File "train.py", line 87, in main
    trainer.end_of_epoch(data, current_epoch, current_iteration)
UnboundLocalError: local variable 'data' referenced before assignment
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/bin/python3', '-u', 'train.py', '--local_rank=0', '--single_gpu', '--config', 'configs/projects/fs_vid2vid/YouTubeDancing/ampO1.yaml']' returned non-zero exit status 1.

**Comment by arulpraveent** [comment]
@arunmallya Sure the command that i used to create the lmbd dataset is
"python3 scripts/build_lmdb.py --config configs/projects/fs_vid2vid/YouTubeDancing/ampO1.yaml --data_root /mnt/fs/datasets/fsv/jay-arul-long-shot-fsv/train --output_root ~/imaginaire/datasets/youtubeDancing/lmdb/train --paired"

The command that I used to start the training is
"python3 -m torch.distributed.launch --nproc_per_node=1 train.py --single_gpu --config configs/projects/fs_vid2vid/YouTubeDancing/ampO1.yaml"

The stack trace of the error is
Traceback (most recent call last):
File "train.py", line 93, in
main()
File "train.py", line 87, in main
trainer.end_of_epoch(data, current_epoch, current_iteration)
UnboundLocalError: local variable 'data' referenced before assignment
Traceback (most recent call last):
File "/home/ubuntu/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/ubuntu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in
main()
File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/bin/python3', '-u', 'train.py', '--local_rank=0', '--single_gpu', '--config', 'configs/projects/fs_vid2vid/YouTubeDancing/ampO1.yaml']' returned non-zero exit status 1.

**Comment by arunmallya** [comment]
There's some issue in your dataset folder structure or the data specification (`input_types`) in your config. 
Your code is skipping the training loop (https://github.com/NVlabs/imaginaire/blob/master/train.py#L72-L84) and directly going to https://github.com/NVlabs/imaginaire/blob/master/train.py#L87, which is why `data` is not defined.
In other words, `train_data_loader` does not return any batches.
