### ISSUE TITLE
pynvml Issue

### ISSUE THREAD

**Issue by msaad1311** [NVlabs/imaginaire#56]
Hello. I installed the imaginaire library as instructed in the installation guide and when running the fs-vid2vid i am getting the following error 

`pynvml.nvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found`

Can you kindly guide the way forward in this case? I am using Windows 10 with the same CUDA and cuDNN version as mentioned in the Installation guide.

**Comment by arunmallya** [comment]
You can try to remove all calls to this file: https://github.com/NVlabs/imaginaire/blob/master/imaginaire/utils/gpu_affinity.py
This is the only one that uses `pynvml`
