### ISSUE TITLE
windows installtion "AttributeError: module 'os' has no attribute 'sched_setaffinity'"

### ISSUE THREAD

**Issue by simon-eda** [NVlabs/imaginaire#57]
Dear All, 
i installed imaginaire succefully on windows. 
however, i get an error when running inteference.

"AttributeError: module 'os' has no attribute 'sched_setaffinity'"

can you help me to fix the error? 

many thanks,
SImon

**full log:** 
python -m torch.distributed.launch --nproc_per_node=8 train.py \ --config configs/projects/pix2pixhd/cityscapes/ampO1.yaml
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
usage: train.py [-h] --config CONFIG [--logdir LOGDIR]
                [--checkpoint CHECKPOINT] [--seed SEED]
                [--local_rank LOCAL_RANK] [--single_gpu]
                [--num_workers NUM_WORKERS]
train.py: error: unrecognized arguments: \
usage: train.py [-h] --config CONFIG [--logdir LOGDIR]
                [--checkpoint CHECKPOINT] [--seed SEED]
                [--local_rank LOCAL_RANK] [--single_gpu]
                [--num_workers NUM_WORKERS]
train.py: error: unrecognized arguments: \
usage: train.py [-h] --config CONFIG [--logdir LOGDIR]
                [--checkpoint CHECKPOINT] [--seed SEED]
                [--local_rank LOCAL_RANK] [--single_gpu]
                [--num_workers NUM_WORKERS]
train.py: error: unrecognized arguments: \
usage: train.py [-h] --config CONFIG [--logdir LOGDIR]
                [--checkpoint CHECKPOINT] [--seed SEED]
                [--local_rank LOCAL_RANK] [--single_gpu]
                [--num_workers NUM_WORKERS]
train.py: error: unrecognized arguments: \
usage: train.py [-h] --config CONFIG [--logdir LOGDIR]
                [--checkpoint CHECKPOINT] [--seed SEED]
                [--local_rank LOCAL_RANK] [--single_gpu]
                [--num_workers NUM_WORKERS]
train.py: error: unrecognized arguments: \
usage: train.py [-h] --config CONFIG [--logdir LOGDIR]
                [--checkpoint CHECKPOINT] [--seed SEED]
                [--local_rank LOCAL_RANK] [--single_gpu]
                [--num_workers NUM_WORKERS]
train.py: error: unrecognized arguments: \
Traceback (most recent call last):
  File "C:\Users\Simon\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Simon\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Simon\anaconda3\lib\site-packages\torch\distributed\launch.py", line 263, in <module>
    main()
  File "C:\Users\Simon\anaconda3\lib\site-packages\torch\distributed\launch.py", line 259, in main
    usage: train.py [-h] --config CONFIG [--logdir LOGDIR]
                [--checkpoint CHECKPOINT] [--seed SEED]
                [--local_rank LOCAL_RANK] [--single_gpu]
                [--num_workers NUM_WORKERS]
cmd=cmd)usage: train.py [-h] --config CONFIG [--logdir LOGDIR]
                [--checkpoint CHECKPOINT] [--seed SEED]
                [--local_rank LOCAL_RANK] [--single_gpu]
                [--num_workers NUM_WORKERS]

subprocesstrain.py: error: unrecognized arguments: \
train.py: error: unrecognized arguments: \
.CalledProcessError: Command '['C:\\Users\\Simon\\anaconda3\\python.exe', '-u', 'train.py', '--local_rank=7', '\\', '--config', 'configs/projects/pix2pixhd/cityscapes/ampO1.yaml']' returned non-zero exit status 2.
(base) PS C:\Users\Simon\v2v\imaginaire> python scripts/download_test_data.py --model_name pix2pixhd
Test data exists at projects/pix2pixhd/test_data
(base) PS C:\Users\Simon\v2v\imaginaire> python inference.py --single_gpu  --config configs/projects/pix2pixhd/cityscapes/ampO1.yaml  --output_dir projects/pix2pixhd/output/cityscapes
Traceback (most recent call last):
  File "inference.py", line 91, in <module>
    main()
  File "inference.py", line 39, in main
    set_affinity(args.local_rank)
  File "C:\Users\Simon\v2v\imaginaire\imaginaire\utils\gpu_affinity.py", line 57, in set_affinity
    os.sched_setaffinity(0, dev.getCpuAffinity())
AttributeError: module 'os' has no attribute 'sched_setaffinity'

**Comment by arunmallya** [comment]
Please comment this line: https://github.com/NVlabs/imaginaire/blob/master/inference.py#L39
It is an optional trick to improve performance.
