### ISSUE TITLE
UnboundLocalError: local variable 'data' referenced before assignment

### ISSUE THREAD

**Issue by arulpraveent** [NVlabs/imaginaire#58]
@arunmallya I opened this new issue since you closed the last one as far as I have checked I haven't made and any changes to the directory structure it's as same as the one mentioned in the readme file and I haven't made any changes to the input configuration too so I'm not sure why this error is showing up.

Dir Sturcture
+---test
|   +---human_instance_maps
|   |   +---seq0001
|   |   \---seq0002
|   +---images
|   |   +---seq0001
|   |   \---seq0002
|   +---poses-openpose
|   |   +---seq0001
|   |   \---seq0002
|   \---pose_maps-densepose
|       +---seq0001
|       \---seq0002
\---train
    +---human_instance_maps
    |   +---seq0001
    |   \---seq0002
    +---images
    |   +---seq0001
    |   \---seq0002
    +---poses-openpose
    |   +---seq0001
    |   \---seq0002
    \---pose_maps-densepose
        +---seq0001
        \---seq0002

the images have .jpg extension and the instance_maps and pose_maps have .png extension the name of the files in each dir are the same too

Error stack
Traceback (most recent call last):
File "train.py", line 93, in
main()
File "train.py", line 87, in main
trainer.end_of_epoch(data, current_epoch, current_iteration)
UnboundLocalError: local variable 'data' referenced before assignment
Traceback (most recent call last):
File "/home/ubuntu/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/home/ubuntu/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in
main()
File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/bin/python3', '-u', 'train.py', '--local_rank=0', '--single_gpu', '--config', 'configs/projects/fs_vid2vid/YouTubeDancing/ampO1.yaml']' returned non-zero exit status 1.

 The command that i used to create the lmbd dataset is
"python3 scripts/build_lmdb.py --config configs/projects/fs_vid2vid/YouTubeDancing/ampO1.yaml --data_root /mnt/fs/datasets/fsv/jay-arul-long-shot-fsv/train --output_root ~/imaginaire/datasets/youtubeDancing/lmdb/train --paired"

**Comment by arunmallya** [comment]
Could you provide me a small sample of your dataset as well as your config?

**Comment by arulpraveent** [comment]
Sure the files you requested are in this drive folder

[https://drive.google.com/drive/folders/1awLdJqYqtxWHRoyb7fL5wpHXIR4FVk1Q?usp=sharing](url)

**Comment by arulpraveent** [comment]
@arunmallya Sure the files you requested are in this drive folder

[https://drive.google.com/drive/folders/1awLdJqYqtxWHRoyb7fL5wpHXIR4FVk1Q?usp=sharing](url)

**Comment by arulpraveent** [comment]
@arunmallya Sure has invited you to a private repository that has the files that you have asked for.

**Comment by tcwang0509** [comment]
This error usually means your batch size is large than the dataset size. What's your batch size now?

**Comment by jiangtianjie2021** [comment]
> 

Have you solved this problem, I also encountered this problem
