### ISSUE TITLE
RuntimeError for linux when using test_train

### ISSUE THREAD

**Issue by jiali1025** [NVlabs/imaginaire#6]
Hi,
I get the following runtime error. My system is ubuntu 18.04 and I used anaconda 3. I installed pytorch with cuda-toolkit 10.02 by using conda install. 

RuntimeError: apex.optimizers.FusedAdam requires cuda extensions

Does this runtime error come from the cudnn? If I sign up the account and download from the Nvidia website which folder I need to put in. Do I need to put it into my anaconda env for this project or my main usr/local/lib ?

Many thanks!

Kindly Regards,

Jiali Li

**Comment by xunhuang1995** [comment]
Your apex is not correctly installed. If you are using pytorch built with cuda 10.2, you also need to have cuda 10.2 installed on your system (/usr/local/cuda) when installing apex.

**Comment by mingyuliutw** [comment]
`pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
`
You need to build apex with **--cuda_ext**

https://github.com/NVIDIA/apex
