### ISSUE TITLE
Model average - setting "self.dim = 0" when removing spectral norm

### ISSUE THREAD

**Issue by schrute99** [NVlabs/imaginaire#61]
Hi,

I have noticed that you set self.dim = 0 in the [ModelAverage](https://github.com/NVlabs/imaginaire/blob/master/imaginaire/utils/model_average.py) class (line 79).

This means that for the modules with spectral norm, the weights are not reshaped before computing the spectral norm (see line 175). 

Shouldn't the dimension depend on the module type (linear, conv, etc) as it is [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/utils/spectral_norm.py) in line 264 ?

Thank you!

**Comment by mingyuliutw** [comment]
This is only applied to the module where the spectral norm is removed. It shouldn't be an issue.
