### ISSUE TITLE
Flownet2 and cuda 11.1

### ISSUE THREAD

**Issue by crenaudineau** [NVlabs/imaginaire#63]
Hello,

How I can install flownet2 with RTX 3090 and cuda 11.1 ? It's only works on pytorch==1.0.1.

Someone has installed / builded flownet2 for vid2vid project on Pytorch 1.8 and cuda 11.1 ?

Thanks

**Comment by mingyuliutw** [comment]
The recent update of the code should address the issue. If not, please reopen it.
