### ISSUE TITLE
what is 1hF8vS6YeHkx3j2pfCeQqqZGwA_PJq_Da and where to put it

### ISSUE THREAD

**Issue by guofengming11-chinese** [NVlabs/imaginaire#65]
When I run "inference.py" **offline**, I don’t know what “**1hF8vS6YeHkx3j2pfCeQqqZGwA_PJq_Da**” needs to be downloaded, and I don’t know **where** to put it after downloading

**Comment by EricHuiK** [comment]
me to

**Comment by mingyuliutw** [comment]
We put checkpoints and some example data in google drive. **1hF8vS6YeHkx3j2pfCeQqqZGwA_PJq_Da** is the id of the file in google drive. Did you encounter downloading issues?
