### ISSUE TITLE
pretrained_weight url

### ISSUE THREAD

**Issue by guofengming11** [NVlabs/imaginaire#66]
thank you for sharing
there's no pretrained_weight in the   YouTubeDancing/ampO1.yaml   
Could you please send  a complete document    **YouTubeDancing/ampO1.yaml**   ？
Thank you very much！

**Comment by git-hamza** [comment]
Have your figure out this one?

**Comment by achen353** [comment]
@git-hamza  @guofengming11 Have you resolved this?

**Comment by mingyuliutw** [comment]
We do not plan to provide documentation for the config file as the functions of the variables are self-explained as one traces the code. We also try to make the names as meaningful as much.
