### ISSUE TITLE
How to test vid2vid without "images"?

### ISSUE THREAD

**Issue by MultiPath** [NVlabs/imaginaire#67]
Hi,

We are using the vid2vid part for video translation.
At inference time, we only have the input "seg_maps" as input video. 
The code raises errors as 
```
  _File "imaginaire/imaginaire/trainers/vid2vid.py", line 353, in test
    key = data['key']['images'][0][0]
KeyError: 'images'
```
I assume it refers to the target images which is not available at test time.
How can we write the yaml file in this case?

**Comment by mingyuliutw** [comment]
Please check scripts/test_inference.sh
