### ISSUE TITLE
inference on fs-vid-to-vid

### ISSUE THREAD

**Issue by SURABHI-GUPTA** [NVlabs/imaginaire#69]
@arunmallya @dumerrill @mjgarland hey.. thanks for sharing your code.
I tried running your face-forensics pre-trained model on custom reference test data, however, the results are not good.

Can you suggest anything I should try?

https://user-images.githubusercontent.com/22388014/115153448-8e1f8880-a093-11eb-8731-82414e5795c6.mp4

**Comment by mingyuliutw** [comment]
Source images are important for getting good motion transfer performance for few-shot vid2vid.

**Comment by grewe** [comment]
@SURABHI-GUPTA  we are having problems with inference and was hoping you could share your config file and any tips --or if you saw this same error  [https://github.com/NVlabs/imaginaire/issues/112](https://github.com/NVlabs/imaginaire/issues/112 )

**Comment by grewe** [comment]
@tcwang0509 any idea about this....using the new config file from issue 106 we got from you results in this new issue and we have been through all the code and using even same data from training and fails.   Please advise

**Comment by grewe** [comment]
If step_count is a variable that pytorch shoudl be supporting ---there is at least some kind of conflict and we are using the same version as was used recently in discussions with arun, etc.

**Comment by grewe** [comment]
If instead _step_count is a variable that should be maintained in the imaginaire code, we can not find any place it is initialized from doing a backward search from the error into the code
