### ISSUE TITLE
FUNIT on street scenarios

### ISSUE THREAD

**Issue by fabvio** [NVlabs/imaginaire#78]
Hello,
thanks for your amazing work. We're trying to use FUNIT and COCO-FUNIT as baselines for our recent project. We usually work with street scenes. However, the default configuration parameters seem to fail completely when the network is trained on street scenarios like cityscapes. Is there any valid configuration guaranteeing acceptable results in those environments?
Thanks in advance.

**Comment by mingyuliutw** [comment]
We haven't tested FUNIT and COCO-FUNIT on street datasets. We do not have a yaml file to share.

But I can say that for street dataset, usually, we prefer fewer downsampling steps for the generator and discriminator. You could change num_downsamples_content from 4 to 2 or something. 
https://github.com/NVlabs/imaginaire/blob/7c650977b29ea2dd12557d1fef447df9809db737/configs/projects/coco_funit/animal_faces/base64_bs8_class119.yaml#L46

**Comment by fabvio** [comment]
Great, thanks for your answer, I will give it a try. Closing the issue.
