### ISSUE TITLE
How to download  the pretrained  model   and data for coco_funit???

### ISSUE THREAD

**Issue by c1a1o1** [NVlabs/imaginaire#80]
How to download  the pretrained  model   and data for coco_funit???

**Comment by mingyuliutw** [comment]
dataset set available at
https://github.com/NVlabs/imaginaire/tree/master/projects/funit

when you run the inference command in
https://github.com/NVlabs/imaginaire/tree/master/projects/coco_funit

it will download the pretrained model

**Comment by c1a1o1** [comment]
Thanks  a lot!
