### ISSUE TITLE
[vid2vid] train with cityscapes dataset

### ISSUE THREAD

**Issue by puhuk** [NVlabs/imaginaire#84]
I got below error when train with this command

`python -m torch.distributed.launch --nproc_per_node=1 train.py --config configs/projects/vid2vid/cityscapes/ampO1.yaml --single_gpu`

`ValueError: Num channels: 4. One-hot expansion can only be done if image has 1 channel`

It seems my seg_maps have 4 channels.

I download from Cityscape dataset (https://www.cityscapes-dataset.com/downloads/)

leftImg8bit_trainvaltest.zip (11GB) [md5] and gtFine_trainvaltest.zip (241MB) [md5]

When I run below scripts for each train and val set, it succeeded.

Do I need to use other label dataset? or how can I fix this.

**Comment by DanAmador** [comment]
Did you manage to fully train the model?

**Comment by arunmallya** [comment]
As stated in the error, use segmentation maps that have a single channel to indicate class index. Else, modify the code to handle your case.

**Comment by Lucky0775** [comment]
> 使用此命令训练时出现以下错误
> 
> `python -m torch.distributed.launch --nproc_per_node=1 train.py --config configs/projects/vid2vid/cityscapes/ampO1.yaml --single_gpu`
> 
> `ValueError: Num channels: 4. One-hot expansion can only be done if image has 1 channel`
> 
> 看来我的 seg_maps 有 4 个频道。
> 
> 我从 Cityscape 数据集下载（https://www.cityscapes-dataset.com/downloads/）
> 
> leftImg8bit_trainvaltest.zip (11GB) [md5] 和 gtFine_trainvaltest.zip (241MB) [md5]
> 
> 当我为每个火车和验证集运行以下脚本时，它成功了。
> 
> 我需要使用其他标签数据集吗？或者我该如何解决这个问题。

Hi,Did you train the cityscapes dataset successfully? Can you provide some training steps？
