### ISSUE TITLE
What's the format for all_filenames.json of UNIT dataset

### ISSUE THREAD

**Issue by JustLuoyu** [NVlabs/imaginaire#88]
I'd like to train UNIT on my own dataset, what's the format for all_filenames.json and also the directory architecture

**Comment by mingyuliutw** [comment]
Thanks for the question. I have updated the project page for UNIT to address your question.

## Training
The procedure for training is very similar to the procedure of training for [MUNIT](../munit/README.md). Please checkout [the project page of MUNIT](../munit/README.md) for details.
