### ISSUE TITLE
fs_vid2vid:  Need documentation on configuration file amp01.yaml documentation

### ISSUE THREAD

**Issue by grewe** [NVlabs/imaginaire#92]
I have looked online and can not find any documentation of the parameters found in the imagainaire fs_vid2vid amp01.yaml configuration file.  I need to understand what are the options especially for training but, testing also.  Is there anyone that can provide this --otherwise it is like using a framework with no instructions whatsoever. 

Thanks

**Comment by mingyuliutw** [comment]
Sorry for the inconvenience. We do not plan to provide documentation for the config file as the functions of the variables are self-explained as one traces the code. We also try to make the names as meaningful as much.

**Comment by grewe** [comment]
Unfortunately, many are not understandable and tracing the code for all of them takes an enormous amount of time that is repeated by each person.   The amount of time it would take a developer that knows it ---30 minutes at most ---would save so many people hours and hours and hours of time

**Comment by mingyuliutw** [comment]
For commercial use, please consult https://www.nvidia.com/en-us/research/inquiries/

**Comment by grewe** [comment]
Thanks we are in a university for education purposes only not commercial.
Unfortunately, at a state university we do not have a budget to pursue
commercial services

Lynne Grewe |  Professor Computer Science, Director iLab |  California
State University East Bay |
***@***.*** ***@***.***>  *
