### ISSUE TITLE
Other Resolutions in SPADE 

### ISSUE THREAD

**Issue by jpapon** [NVlabs/imaginaire#94]
Hello,

Trying out training the SPADE model in this library, and it works fine at 256x256.
If I adjust the resize_smallest_side in base128_bs4.yaml to one of the other two values allowed in spade.py (512 or 1024), my generated images always turn out blank white.

Any idea why? Is there some other setting I need to adjust?

**Comment by mingyuliutw** [comment]
Just to understand your setting a bit more. Are you training a new model with 512 or 1024 smallest side? Or are you doing inference with a 256 model but aiming to generate 512 or 1024 resolution images?

**Comment by jpapon** [comment]
Training a new model with 512 or 1024 on the smallest side. 
The model seems to train fine, but the samples saved every `image_save_iter` come out blank.

Same data and configuration (other than the different smallest side and crop) trains and outputs sample images just fine at 256.

**Comment by arunmallya** [comment]
Please set the `gen.output_multiplier` parameter in the config to `0.5` for 512 output models, and `0.33` for 1024 output models. See https://github.com/NVlabs/imaginaire/blob/master/configs/projects/spade/landscapes/lhq.yaml#L9 for usage in a 512 model.

Using the default value of `1`, which is appropriate for 256 models makes the tanh saturate and not provide useful gradients. See https://github.com/NVlabs/imaginaire/blob/master/imaginaire/generators/spade.py#L491 and https://github.com/NVlabs/imaginaire/blob/master/imaginaire/generators/spade.py#L505 for details. `output_multiplier` acts like an averaging factor.

**Comment by jpapon** [comment]
Excellent, thank you!
