### ISSUE TITLE
Where SPADE/GauGAN saves checkpoints? how to load them into inference.py?

### ISSUE THREAD

**Issue by Kitty-sunray** [NVlabs/imaginaire#99]
So far many epochs gone and no checkpoint was saved in my training, despite "snapshot_save_epoch: 1" in the config.
train.py  has parameter "checkpoint" but it is not for saving path of checkpoints
What is 'val' part of dataset? is it necessary for training to train properly or is it just for user to see how good model performs at each epoch?

**Comment by arunmallya** [comment]
Val is used to determine the quality of the model before saving. The checkpoints should be saved in the `logs/` directory.

**Comment by Kitty-sunray** [comment]
I mean, is "val" folders affects training in any way? or is it just for human to see? Can I have empty "val" folder and successfully train?

**Comment by arunmallya** [comment]
val does not affect training, but it might break the training loop if no val folder is found. You can provide a subset of train as val set in that case.
